// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xkrtbwecvfdeqfkvrdcb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhrcnRid2VjdmZkZXFma3ZyZGNiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI1NTM1MTgsImV4cCI6MjA2ODEyOTUxOH0.r0CBSxSXqgNXgrnRvNvkra9swGCYuS8R1VKRhrLTcIs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});